[General]
ScreenWidth="3840"
ScreenHeight="2160"

Font="Noto Sans"
FontSize="18"

RoundCorners="12"

HourFormat="HH:mm"
DateFormat="dddd, d MMMM"

HeaderText=""

Background="Backgrounds/aether.jpg"
DimBackground="0.4"
CropBackground="true"

HeaderTextColor="{{ foreground }}"
DateTextColor="{{ foreground }}"
TimeTextColor="{{ foreground }}"

FormBackgroundColor="{{ background }}"
BackgroundColor="{{ background }}"
DimBackgroundColor="{{ background }}"

LoginFieldBackgroundColor="{{ color0 }}"
PasswordFieldBackgroundColor="{{ color0 }}"
LoginFieldTextColor="{{ foreground }}"
PasswordFieldTextColor="{{ foreground }}"
UserIconColor="{{ color4 }}"
PasswordIconColor="{{ color4 }}"

PlaceholderTextColor="{{ color8 }}"
WarningColor="#e35149"

LoginButtonTextColor="{{ background }}"
LoginButtonBackgroundColor="{{ color4 }}"
SystemButtonsIconsColor="{{ color4 }}"
SessionButtonTextColor="{{ color4 }}"

HighlightTextColor="{{ background }}"
HighlightBackgroundColor="{{ color4 }}"
HighlightBorderColor="transparent"

HoverUserIconColor="{{ foreground }}"
HoverPasswordIconColor="{{ foreground }}"
HoverSystemButtonsIconsColor="{{ foreground }}"

PartialBlur="true"
BlurMax="8"
Blur="2.0"
HaveFormBackground="true"
FormPosition="center"

HideVirtualKeyboard="true"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
