#!/bin/bash
# Aplică wallust pe o imagine și reîncarcă toate aplicațiile

exec >> /tmp/wallust-apply.log 2>&1
echo "=== $(date) === IMAGE: $1"

# Resolve real path (avoid circular symlinks when called with last-wallpaper itself)
IMAGE=$(readlink -f "$1" 2>/dev/null)
[ -z "$IMAGE" ] && echo "Usage: wallust-apply.sh <image>" && exit 1
[ ! -f "$IMAGE" ] && echo "File not found: $IMAGE" && exit 1

# Salvează ultimul wallpaper pentru boot (symlink la fișierul real)
ln -sf "$IMAGE" "$HOME/.config/wallust/last-wallpaper"

# Generează culorile și template-urile
wallust run "$IMAGE" -q

# Setează wallpaper (moștenește WAYLAND_DISPLAY din mediu)
awww img "$IMAGE" --transition-type fade --transition-duration 1 2>/dev/null

# Alege culoarea cu cea mai mare saturație din întreaga paletă wallust
bg=$(grep 'background' ~/.config/waybar/aether-colors.css | grep -oP '#[0-9a-fA-F]+' | head -1)
fg=$(grep 'foreground' ~/.config/waybar/aether-colors.css | grep -oP '#[0-9a-fA-F]+' | head -1)
hl=$(grep 'highlight' ~/.config/waybar/aether-colors.css | grep -oP '#[0-9a-fA-F]+' | head -1)

# Caută cea mai saturată culoare din paleta wallust (color0-color15)
best_accent=$(python3 - <<'EOF'
import colorsys, re

colors_file = open("/home/alex/.cache/wallust/sequences").read()
hexes = re.findall(r'#([0-9a-fA-F]{6})', colors_file)

best = None
best_sat = -1
for h in hexes:
    r, g, b = int(h[0:2],16)/255, int(h[2:4],16)/255, int(h[4:6],16)/255
    _, s, v = colorsys.rgb_to_hsv(r, g, b)
    if s > best_sat and v > 0.2:
        best_sat = s
        best = '#' + h
print(best or '#888888')
EOF
)
# Usa cea mai saturată ca accent pentru border (dacă e semnificativ mai bună)
[ -n "$best_accent" ] && hl="$best_accent"
STYLE="$HOME/.config/waybar/style.css"
sed -i "s|@define-color background .*|@define-color background $bg;|" "$STYLE"
sed -i "s|@define-color foreground .*|@define-color foreground $fg;|" "$STYLE"
sed -i "s|@define-color highlight .*|@define-color highlight $hl;|" "$STYLE"

# Extended palette from ghostty (generated by wallust)
GHOST="$HOME/.config/ghostty/colors.conf"
if [ -f "$GHOST" ]; then
    c2=$(grep 'palette = 2='  "$GHOST" | grep -oP '#[0-9a-fA-F]+')
    c3=$(grep 'palette = 3='  "$GHOST" | grep -oP '#[0-9a-fA-F]+')
    c5=$(grep 'palette = 5='  "$GHOST" | grep -oP '#[0-9a-fA-F]+')
    c6=$(grep 'palette = 6='  "$GHOST" | grep -oP '#[0-9a-fA-F]+')
    c7=$(grep 'palette = 7='  "$GHOST" | grep -oP '#[0-9a-fA-F]+')
    [ -n "$c6" ] && sed -i "s|@define-color w-warm .*|@define-color w-warm    $c6;|" "$STYLE"
    [ -n "$c7" ] && sed -i "s|@define-color w-light .*|@define-color w-light   $c7;|" "$STYLE"
    [ -n "$c5" ] && sed -i "s|@define-color w-neutral .*|@define-color w-neutral $c5;|" "$STYLE"
    [ -n "$c3" ] && sed -i "s|@define-color w-muted .*|@define-color w-muted   $c3;|" "$STYLE"
    [ -n "$c2" ] && sed -i "s|@define-color w-dark .*|@define-color w-dark    $c2;|" "$STYLE"

    # Update calendar colors in config.jsonc
    CONFIG="$HOME/.config/waybar/config.jsonc"
    [ -n "$hl" ] && sed -i '/[[:space:]]*"weekdays"/ s|color='"'"'[^'"'"']*'"'"'|color='"'"''"$hl"''"'"'|' "$CONFIG"
    [ -n "$c6" ] && sed -i '/[[:space:]]*"today"/    s|color='"'"'[^'"'"']*'"'"'|color='"'"''"$c6"''"'"'|' "$CONFIG"
    [ -n "$c7" ] && sed -i '/[[:space:]]*"weekend"/  s|color='"'"'[^'"'"']*'"'"'|color='"'"''"$c7"''"'"'|' "$CONFIG"
    [ -n "$c3" ] && sed -i '/[[:space:]]*"days"[^s]/ s|color='"'"'[^'"'"']*'"'"'|color='"'"''"$c3"''"'"'|' "$CONFIG"
fi

# Restore saved power profile
SAVED_PROFILE=$(cat "$HOME/.local/state/power-profile" 2>/dev/null || echo "balanced")
sudo /usr/local/bin/set-power-profile "$SAVED_PROFILE" 2>/dev/null

# Reload waybar CSS
pkill -SIGUSR2 waybar 2>/dev/null

# Reîncarcă mako
makoctl reload 2>/dev/null

# Actualizează hyprlock culori și wallpaper
accent="$hl"
if [ -n "$accent" ]; then
    r=$((16#${accent:1:2}))
    g=$((16#${accent:3:2}))
    b=$((16#${accent:5:2}))
    sed -i "s|check_color = .*|check_color = rgba($r, $g, $b, 0.8)|" "$HOME/.config/hypr/hyprlock.conf"
    sed -i "s|outer_color = .*|outer_color = rgba($r, $g, $b, 0.3)|" "$HOME/.config/hypr/hyprlock.conf"
fi
sed -i "s|^    path = .*|    path = $IMAGE|" "$HOME/.config/hypr/hyprlock.conf"

# GTK theme
mkdir -p "$HOME/.config/gtk-3.0"
cp "$HOME/.config/gtk-4.0/gtk.css" "$HOME/.config/gtk-3.0/gtk.css" 2>/dev/null
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null

# SDDM: copiază wallpaper-ul și config-ul cu culori (necesită sudo)
if [ -f "$HOME/.config/wallust/sddm-aether-generated.conf" ]; then
    sudo /usr/local/bin/sddm-update-theme \
        "$IMAGE" \
        "$HOME/.config/wallust/sddm-aether-generated.conf"
fi

# Actualizează border Hyprland (activ + inactiv)
if [ -n "$accent" ] && [ -n "$bg" ]; then
    hyprctl eval "hl.config({general = {col = {active_border = 'rgba(${accent:1}ee)', inactive_border = 'rgba(${bg:1}aa)'}}})" 2>/dev/null
fi
