background = #383839
foreground = #DEE6E5
palette = 0=#383839
palette = 1=#2E4754
palette = 2=#5D5C4F
palette = 3=#58767E
palette = 4=#898674
palette = 5=#86A3A6
palette = 6=#CDDDDC
palette = 7=#DEE6E5
palette = 8=#9BA1A0
palette = 9=#2E4754
palette = 10=#5D5C4F
palette = 11=#58767E
palette = 12=#898674
palette = 13=#86A3A6
palette = 14=#CDDDDC
palette = 15=#DEE6E5
